site_name: Play Store - Requisitos de Software
repo_name: Requisitos de Software - Play Store
repo_url: https://github.com/artrsousa1/req2024-1

nav:
  - Início: index.md
  - Projeto: home/home.md
  - Apresentações: apresentacoes/apresentacoes.md
  - 'Reuniões':
    - Reuniões: reunioes/reunioes.md
    - Reunião01: reunioes/reuniao01.md
    - Reunião02: reunioes/reuniao02.md
    - Reunião03: reunioes/reuniao03.md
    - Reunião04: reunioes/reuniao04.md
    - Reunião05: reunioes/reuniao05.md
    - Reunião06: reunioes/reuniao06.md
    - Reunião07: reunioes/reuniao07.md
    - Reunião08: reunioes/reuniao08.md
    - Reunião09: reunioes/reuniao09.md
    - Reunião10: reunioes/reuniao10.md
    - Reunião11: reunioes/reuniao11.md
    - Reunião12: reunioes/reuniao12.md
    - Reunião13: reunioes/reuniao13.md
    - Reunião14: reunioes/reuniao14.md
    - Reunião15: reunioes/reuniao15.md
    - Reunião16: reunioes/reuniao16.md
    - Reunião17: reunioes/reuniao17.md
    - Reunião18: reunioes/reuniao18.md


  - Pré-Rastreabilidade: 
    - Pré-rastreabilidade: 'pre-ras/pre-ras.md'
    - Geral: 'pre-ras/geral.md'
    - Apps: 'pre-ras/apps.md'
    - Fluxo de usuário: 'pre-ras/fluxo_usuario.md'
    - Jogos: 'pre-ras/jogos.md'
  - 'Elicitação':
    - Elicitação: 'elicitacao/tecnicas.md'
    - Requisitos elicitados: 'elicitacao/elicitacao.md'
    - Perfil: 'elicitacao/perfil.md'
    - Personas: 'elicitacao/personas.md'
    - Apps: 'elicitacao/apps.md'
    - Fluxo de usuário: 'elicitacao/fluxo_usuario.md'
    - Jogos: 'elicitacao/jogos.md'
    - Não funcionais: 'elicitacao/nao_funcionais.md'
  - 'Modelagem':
    - Modelagem: 'modelagem/modelagem.md'
    - 'Tradicional':
      - Tradicional: 'modelagem/tradicional/tradicional.md'
      - Cenários: 'modelagem/tradicional/cenarios.md'
      - Léxico: 'modelagem/tradicional/lexico.md'
    - 'OO':
      - Orientação a objetos: 'modelagem/OO/oo.md'
      - Caso de uso: 'modelagem/OO/caso-uso.md'
      - Especificação suplementar: 'modelagem/OO/especificacao_suplementar.md'
    - 'Ágil':
      - Metodologia Ágil: 'modelagem/agil/agil.md'
      - Backlog: 'modelagem/agil/backlog.md'
      - História de usuário: 'modelagem/agil/criterio.md'
    - 'GORE': 
      - GORE: 'modelagem/GORE/gore.md'
      - NFR: 'modelagem/GORE/nfrFramework.md'
      - I*: 'modelagem/GORE/istar.md'

  - 'Análise':
      - Análise: analise/analise.md
      - Sugestão de nova funcionalidade: analise/prototipo.md
      - Checklist: analise/checklist.md

  - 'Rastreabilidade': 
      - Rastreabilidade: rastreabilidade/rastreabilidade.md
      - Matriz de rastreabilidade: rastreabilidade/matriz.md
      - Pós rastreabilidade: rastreabilidade/pos-rastreabilidade.md

theme:
  name: material
  icon: 
    repo: fontawesome/brands/github

  font:
    text: Poppins

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.footer
    - navigations.indexes
    - content.code.copy
    - toc.integrate
    - search.suggest
    - search.highlight  

  nav_style: dark
  language: pt
  repo: fontawesome/brands/github
  logo: assets/imagens/google_play.png
  favicon: assets/google_play.ico

  palette:
    - scheme: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Alternar para modo escuro
      primary: blue
      accent: indigo

    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Alternar para modo claro
      primary: black
      accent: light blue
  
  markdown_extensions:
    - pydownx.arithmatex:
        generic: true
    - pydownx.highlight:
        anchor_linenums: true
        line_spans: __span
      pigments_lang_class: true
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.inlinehilite
    - admonition
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - pymdownx.snippets
