site_name: Play Store - Requisitos de Software
repo_name: Requisitos de Software - Play Store
repo_url: https://github.com/artrsousa1/req2024-1

nav:
  - Início: index.md
  - Projeto: home/home.md
  - Apresentações: apresentacoes/apresentacoes.md
  - 'Reuniões':
    - Reuniões: reunioes/reunioes.md
    - Reunião01: reunioes/reuniao01.md
    - Reunião02: reunioes/reuniao02.md
    - Reunião05: reunioes/reuniao05.md
  - Pré-Rastreabilidade: 
    - Pré-rastreabilidade: 'pre-ras/pre-ras.md'
    - Geral: 'pre-ras/geral.md'
    - Apps: 'pre-ras/apps.md'
    - Fluxo de usuário: 'pre-ras/fluxo_usuario.md'
    - Jogos: 'pre-ras/jogos.md'
  - 'Elicitação':
    - Elicitação: 'elicitacao/tecnicas.md'
    - Requisitos elicitados: 'elicitacao/elicitacao.md'
    - Perfil: 'elicitacao/perfil.md'
    - Apps: 'elicitacao/apps.md'
    - Fluxo de usuário: 'elicitacao/fluxo_usuario.md'
    - Jogos: 'elicitacao/jogos.md'
  - Modelagem: modelagem/modelagem.md
  - Análise: analise/analise.md
  - Rastreabilidade: rastreabilidade/rastreabilidade.md

theme:
  name: material
  icon: 
    repo: fontawesome/brands/github

  font:
    text: Poppins

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.footer
    - navigations.indexes
    - content.code.copy
    - toc.integrate
    - search.suggest
    - search.highlight  

  nav_style: dark
  language: pt
  repo: fontawesome/brands/github
  logo: assets/imagens/google_play.png
  favicon: assets/google_play.ico

  palette:
    - scheme: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Alternar para modo escuro
      primary: blue
      accent: indigo

    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Alternar para modo claro
      primary: black
      accent: light blue
  
  markdown_extensions:
    - pydownx.arithmatex:
        generic: true
    - pydownx.highlight:
        anchor_linenums: true
        line_spans: __span
      pigments_lang_class: true
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.inlinehilite
    - admonition
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - pymdownx.snippets
